
services:
  - type: web
    name: rnchealth
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./render_start.sh"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "rnchealth.onrender.com,127.0.0.1,localhost"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true