# Generated by Django 6.0.2 on 2026-05-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultantavailability',
            unique_together={('consultant', 'day_of_week', 'start_time')},
        ),
    ]
