# Generated by Django 6.0.2 on 2026-05-22 14:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('call_type', models.CharField(choices=[('video', 'Video Call'), ('audio', 'Audio Call')], default='video', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('initiated', 'Initiated'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='initiated', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('consultant_quality', models.CharField(blank=True, max_length=20)),
                ('technical_issues', models.TextField(blank=True)),
                ('connection_type', models.CharField(blank=True, choices=[('p2p', 'Peer-to-Peer'), ('relay', 'Relay (TURN)'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('connection_quality', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('failed', 'Failed'), ('not_tested', 'Not Tested')], default='not_tested', max_length=20)),
                ('webrtc_stats', models.JSONField(blank=True, default=dict, help_text='WebRTC connection statistics and metrics')),
                ('offer_exchanged', models.BooleanField(default=False)),
                ('answer_exchanged', models.BooleanField(default=False)),
                ('ice_candidates_count', models.PositiveIntegerField(default=0)),
                ('reconnection_attempts', models.PositiveIntegerField(default=0)),
                ('connection_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('connection_established_at', models.DateTimeField(blank=True, null=True)),
                ('last_ping_timestamp', models.DateTimeField(blank=True, null=True)),
                ('consultant_notes', models.TextField(blank=True)),
                ('patient_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(limit_choices_to={'role': 'consultant'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_calls', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Appointment_type', models.CharField(choices=[('video', 'Video Consultation'), ('audio', 'Auido Consultation'), ('in_person', 'In-Person Visit')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending_confirmation'), ('confirmed', 'confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='Pending', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(15)])),
                ('reason_for_visit', models.TextField(max_length=500)),
                ('patient_notes', models.TextField(blank=True, help_text='Additional_information')),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='consultants.consultantprofile')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
                ('call_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='consultations.callsession')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medications', models.JSONField(default=list)),
                ('instructions', models.TextField()),
                ('diagnosis', models.CharField(choices=[('active', 'Active'), ('completed', 'completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_seesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.callsession')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='consultants.consultantprofile')),
            ],
            options={
                'db_table': 'appointment_slots',
                'indexes': [models.Index(fields=['consultant', 'date', 'is_available'], name='appointment_consult_9c4cbf_idx')],
                'unique_together': {('consultant', 'date', 'start_time')},
            },
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['consultant', 'status'], name='call_sessio_consult_73f142_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['patient', 'status'], name='call_sessio_patient_73ded5_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['session_id'], name='call_sessio_session_546c67_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['scheduled_at'], name='call_sessio_schedul_09d672_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['consultant', 'scheduled_date'], name='appointment_consult_5306b0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'scheduled_date', 'status'], name='appointment_patient_f2d6e9_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_date', 'scheduled_time'], name='appointment_schedul_bbb64e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_9fecd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('consultant', 'scheduled_date', 'scheduled_time')},
        ),
    ]
