# Generated by Django 6.0.2 on 2026-06-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reminder_sent',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reminder_sent_at',
        ),
    ]
